-- creating tables and foreighn keys
   
    CREATE TABLE t_supplier (
        id_supplier NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100000,
        moniker VARCHAR2(12 CHAR) NOT NULL UNIQUE,
        name VARCHAR2(30 CHAR) NOT NULL,
        PRIMARY KEY (id_supplier)
    );
    
    CREATE TABLE t_supply (
        id_supply NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100000,
        code VARCHAR2(30 CHAR) NOT NULL,
        num VARCHAR2(30 CHAR) NOT NULL,
        dt DATE NOT NULL,
        id_supplier NUMBER(10,0) NOT NULL,
        e_state VARCHAR2(10) NOT NULL,
        summa NUMBER(14,2),
        nds NUMBER(14,2),
        PRIMARY KEY (id_supply)
    );
    
    CREATE TABLE t_supply_str (
        id_supply_str NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100000,
        id_supply NUMBER (10,0) NOT NULL,
        num NUMBER(6,0) NOT NULL,
        id_ware NUMBER (10,0) NOT NULL,
        qty NUMBER(6,0) NOT NULL,
        price NUMBER (8,2) NOT NULL, 
        summa NUMBER(14,2),
        nds NUMBER (14,2),
        PRIMARY KEY (id_supply_str)
    );
    
    CREATE TABLE t_ware (
        id_ware NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100000,
        moniker VARCHAR2 (12 CHAR) NOT NULL,
        name VARCHAR2(30 CHAR) NOT NULL,
        id_model number (10,0) NOT NULL,
        sz_orig VARCHAR2(30 CHAR) NOT NULL,
        sz_rus VARCHAR2(30 CHAR) NOT NULL,
        price NUMBER(8,2),
        primary key (id_ware)
    );
    
    CREATE TABLE t_rest (
        id_ware NUMBER(10,0) NOT NULL,
        qty NUMBER(6,0),
        primary key (id_ware)
    );
    
    CREATE TABLE t_rest_hist (
        id_ware NUMBER(10,0) NOT NULL,
        dt_beg DATE NOT NULL,
        dt_end DATE NOT NULL,
        qty NUMBER(6,0),
        primary key (id_ware)
    );
    
    CREATE TABLE t_price_ware (
        --id_price_ware NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100000,
        id_ware NUMBER(10,0) NOT NULL,
        dt_beg DATE NOT NULL,
        dt_end DATE NOT NULL,
        price NUMBER(8,2),
        primary key (id_ware)
    );
    
    CREATE TABLE t_sale_rep (
        id_ware NUMBER(10,0) NOT NULL,
        month DATE NOT NULL,
        inp_qty NUMBER(6,0),
        inp_sum NUMBER(14,2),
        supply_qty NUMBER(6,0),
        supply_sum NUMBER(14,2),
        sale_qty NUMBER(6,0),
        sale_sum NUMBER(14,2),
        out_qty NUMBER(6,0),
        out_sum NUMBER(14,2),
        primary key (id_ware, month)
    );
    
     CREATE TABLE t_sale_str (
        id_sale_str NUMBER(10,0)GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100000,
        id_sale NUMBER(10,0) NOT NULL,
        num NUMBER(6,0),
        id_ware NUMBER(10,0) NOT NULL,
        qty NUMBER(6,0),
        price NUMBER(8,2),
        discount NUMBER(8,6),
        disc_price NUMBER(8,2),
        summa NUMBER(14,2),
        nds NUMBER(14,2),
        primary key (id_sale_str)
    );
    
    CREATE TABLE t_sale (
        id_sale NUMBER(10,0)GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100000,
        num VARCHAR2(30),
        dt DATE,
        id_client NUMBER(10,0) NOT NULL,
        e_state VARCHAR2(10),
        discount NUMBER(8,6),
        summa NUMBER(14,2),
        nds NUMBER(14,2),
        primary key (id_sale)
    );
    
    CREATE TABLE t_client (
        id_client NUMBER(10,0)GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100000,
        id_dept NUMBER(10,0) NOT NULL,
        moniker VARCHAR2(12),
        name VARCHAR2(30),
        is_vip NUMBER(1),
        town VARCHAR2(30),
        primary key (id_client)
    );
    
    CREATE TABLE t_dept (
        id_dept NUMBER(10,0)GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100000,
        name VARCHAR2(30) NOT NULL UNIQUE,
        id_parent NUMBER(10,0),
        primary key (id_dept)
    );
    
    CREATE TABLE t_model (
        id_model NUMBER(10,0)GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100000,
        moniker VARCHAR2(12 CHAR),
        name VARCHAR2(30),
        id_node NUMBER(10,0) NOT NULL,
        grp VARCHAR2(30 CHAR),
        subgrp VARCHAR2(30 CHAR),
        label VARCHAR(30 CHAR),
        price NUMBER(8,2),
        primary key (id_model)
    );
    
    CREATE TABLE t_price_model (
        --id_price_model NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100000,
        id_model NUMBER(10,0),
        dt_beg DATE,
        dt_end DATE,
        price NUMBER(8,2),
        primary key (id_model)
    );
    
    CREATE TABLE t_ctl_node (
        id_ctl_node NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100000,
        id_parent NUMBER(10,0),
        code VARCHAR2(12 CHAR),
        tree_code VARCHAR2(240 CHAR),
        name VARCHAR2(30 CHAR),
        primary key (id_ctl_node)
    );
    
    ALTER TABLE t_supply
        ADD CONSTRAINT supply_supplier_fk 
        FOREIGN KEY (id_supplier) 
        REFERENCES t_supplier;
    
    ALTER TABLE t_supply_str
        ADD CONSTRAINT supply_str_supply_fk 
        FOREIGN KEY (id_supply) 
        REFERENCES t_supply;
    
    ALTER TABLE t_supply_str    
        ADD CONSTRAINT supply_ware_fk 
        FOREIGN KEY (id_ware) 
        REFERENCES t_ware;
        
    ALTER TABLE t_rest_hist    
        ADD CONSTRAINT rest_hist_ware_fk 
        FOREIGN KEY (id_ware) 
        REFERENCES t_ware;
    
    ALTER TABLE t_ctl_node    
        ADD CONSTRAINT node_node_parent_fk 
        FOREIGN KEY (id_parent) 
        REFERENCES t_ctl_node; 
    
    ALTER TABLE t_model    
        ADD CONSTRAINT model_node_fk 
        FOREIGN KEY (id_node) 
        REFERENCES t_ctl_node;
        
    ALTER TABLE t_price_model    
        ADD CONSTRAINT model_price_model_fk 
        FOREIGN KEY (id_model) 
        REFERENCES t_model;
        
    ALTER TABLE t_ware    
        ADD CONSTRAINT model_fk 
        FOREIGN KEY (id_model) 
        REFERENCES t_model;
        
    ALTER TABLE t_price_ware    
        ADD CONSTRAINT price_ware_fk 
        FOREIGN KEY (id_ware) 
        REFERENCES t_ware;
        
    ALTER TABLE t_dept    
        ADD CONSTRAINT dept_dept_parent_fk 
        FOREIGN KEY (id_parent) 
        REFERENCES t_dept;
        
    ALTER TABLE t_client    
        ADD CONSTRAINT client_dept_fk 
        FOREIGN KEY (id_dept) 
        REFERENCES t_dept;
        
    ALTER TABLE t_sale    
        ADD CONSTRAINT sale_client_fk 
        FOREIGN KEY (id_client) 
        REFERENCES t_client;
        
    ALTER TABLE t_sale_str    
        ADD CONSTRAINT sale_ware_fk 
        FOREIGN KEY (id_ware) 
        REFERENCES t_ware;        

COMMIT;
