
@"E:\work\Learning-SQL\PlSQL\creation\_0_drop_tables.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_0_create_tables.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_1_initial_data_population.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_2_t_ware population.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_3_1_t_model_add_price_trigger.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_3_t_model_price population.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_4_1_t_ware_add_price_trigger.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_4_t_ware_price population.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_5_1_t_supply_state_restriction_delete_trigger.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_5_1_t_supply_state_restriction_insert_trigger.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_5_1_t_supply_state_restriction_update_trigger.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_5_1_t_supply_state_ware_qty_change_update_trigger.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_5_t_supply_population.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_6_1_t_supply_str_done_state_restriction_delete_trigger.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_6_1_t_supply_str_done_state_restriction_insert_trigger.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_6_1_t_supply_str_done_state_restriction_update_trigger.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_6_2_t_supply_fill_summa_nds_update_trigger.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_6_2_t_supply_str_fill_summa_nds_insert_trigger.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_6_2_t_supply_str_fill_summa_nds_trigger.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_6_t_supply_str_population.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_7_1_t_sale_state_restriction_delete_trigger.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_7_1_t_sale_state_restriction_insert_trigger.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_7_1_t_sale_state_restriction_update_trigger.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_7_1_t_sale_state_ware_qty_change_update_trigger.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_7_t_sale_population.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_8_1_t_sale_str_done_state_restriction_delete_trigger.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_8_1_t_sale_str_done_state_restriction_insert_trigger.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_8_1_t_sale_str_done_state_restriction_update_trigger.sql"
@"E:\work\Learning-SQL\PlSQL\creation\_8_3_t_sale_str_fill_price_trigger.sql"  
@"E:\work\Learning-SQL\PlSQL\creation\_8_2_t_sale_fill_summa_nds_insert_trigger.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_8_2_t_sale_fill_summa_nds_update_trigger.sql" 
@"E:\work\Learning-SQL\PlSQL\creation\_8_2_t_sale_str_fill_summa_nds_trigger.sql"
@"E:\work\Learning-SQL\PlSQL\creation\_8_t_sale_str_population.sql" 
