CREATE TABLE t_sale (
   id_sale NUMBER(10,0)GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100000,
   num VARCHAR2(30),
   dt DATE NOT NULL,
   id_client NUMBER(10,0) NOT NULL,
   e_state VARCHAR2(10) NOT NULL,
   discount NUMBER(8,6) DEFAULT 0,
   summa NUMBER(14,2),
   nds NUMBER(14,2),
   PRIMARY KEY (id_sale)
)
PARTITION BY RANGE (dt)
SUBPARTITION BY LIST (discount)(
   PARTITION supplies_part1 VALUES LESS THAN (DATE '2019-01-01') TABLESPACE t1 (
      SUBPARTITION sp1_no_discount_sales VALUES (0),
      SUBPARTITION sp1_small_discount_sales VALUES (5, 10, 15, 20),
      SUBPARTITION sp1_medium_discount_sales VALUES(25, 30, 35, 40),
      SUBPARTITION sp1_high_discount_sales VALUES (45, 50)
   ),
   PARTITION supplies_part2 VALUES LESS THAN (DATE '2019-02-01') TABLESPACE t2 (
      SUBPARTITION sp2_no_discount_sales VALUES (0),
      SUBPARTITION sp2_small_discount_sales VALUES (5, 10, 15, 20),
      SUBPARTITION sp2_medium_discount_sales VALUES(25, 30, 35, 40),
      SUBPARTITION sp2_high_discount_sales VALUES (45, 50)
   ),
   PARTITION supplies_part3 VALUES LESS THAN (DATE '2019-03-01') TABLESPACE t3 (
      SUBPARTITION sp3_no_discount_sales VALUES (0),
      SUBPARTITION sp3_small_discount_sales VALUES (5, 10, 15, 20),
      SUBPARTITION sp3_medium_discount_sales VALUES(25, 30, 35, 40),
      SUBPARTITION sp3_high_discount_sales VALUES (45, 50)
   ),
   PARTITION supplies_part4 VALUES LESS THAN (DATE '2019-04-01') TABLESPACE t4(
      SUBPARTITION sp4_no_discount_sales VALUES (0),
      SUBPARTITION sp4_small_discount_sales VALUES (5, 10, 15, 20),
      SUBPARTITION sp4_medium_discount_sales VALUES(25, 30, 35, 40),
      SUBPARTITION sp4_high_discount_sales VALUES (45, 50)
   ),
   PARTITION supplies_part5 VALUES LESS THAN (MAXVALUE) TABLESPACE t5(
      SUBPARTITION sp5_no_discount_sales VALUES (0),
      SUBPARTITION sp5_small_discount_sales VALUES (5, 10, 15, 20),
      SUBPARTITION sp5_medium_discount_sales VALUES(25, 30, 35, 40),
      SUBPARTITION sp5_high_discount_sales VALUES (45, 50)
   )
);

