CREATE TABLE t_sale (
   id_sale NUMBER(10,0)GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100000,
   num VARCHAR2(30),
   dt DATE NOT NULL,
   id_client NUMBER(10,0) NOT NULL,
   e_state VARCHAR2(10) NOT NULL,
   discount NUMBER(8,6) DEFAULT 0,
   summa NUMBER(14,2),
   nds NUMBER(14,2),
   PRIMARY KEY (id_sale)
)
PARTITION BY LIST (discount)(
   PARTITION no_discount_sales VALUES (0) TABLESPACE ts1,
   PARTITION small_discount_sales VALUES (5, 10, 15, 20) TABLESPACE ts2,
   PARTITION medium_discount_sales VALUES(25, 30, 35, 40) TABLESPACE ts3,
   PARTITION high_discount_sales VALUES (45, 50) TABLESPACE ts4
);
