
SET SERVEROUTPUT ON;
@"E:\work\Learning-SQL\PlSQL\test\ctl_node_tree_code_insert_test.sql" 
@"E:\work\Learning-SQL\PlSQL\test\ctl_node_tree_code_update_test.sql" 
@"E:\work\Learning-SQL\PlSQL\test\department_no_cycle_restriction_test.sql" 
@"E:\work\Learning-SQL\PlSQL\test\model_add_price_trigger_test.sql" 
@"E:\work\Learning-SQL\PlSQL\test\supply_autocomplete_restriction_test.sql" 
@"E:\work\Learning-SQL\PlSQL\test\supply_done_status_update_restriction_test.sql" 
@"E:\work\Learning-SQL\PlSQL\test\supply_sales_report_update_test.sql" 
@"E:\work\Learning-SQL\PlSQL\test\supply_state_restrictions_test.sql" 
@"E:\work\Learning-SQL\PlSQL\test\supply_str_autocomplete_restriction_test.sql" 
@"E:\work\Learning-SQL\PlSQL\test\supply_str_fill_fields_on_delete_test.sql" 
@"E:\work\Learning-SQL\PlSQL\test\supply_str_fill_fields_on_insert_test.sql" 
@"E:\work\Learning-SQL\PlSQL\test\supply_str_fill_fields_on_update_test.sql" 
@"E:\work\Learning-SQL\PlSQL\test\supply_str_state_restrictions_test.sql" 
@"E:\work\Learning-SQL\PlSQL\test\supply_ware_rest_history_update_test.sql" 
@"E:\work\Learning-SQL\PlSQL\test\supply_ware_rest_update_test.sql" 
@"E:\work\Learning-SQL\PlSQL\test\ware_add_price_trigger_test.sql" 
